# nnictl create --config ./auto_hyper/nni_config.yaml --port 8070
experimentName: Your_Experiment_Name
max_trial_number: 100

searchSpaceFile: search_space.json

trialCommand: python main.py dataset="Toys and Games" output_dir="/home/zsj/models/TEST" model.batch_size=256 model.learning_rate=0.001 model.num_epochs=1

trialCodeDirectory: ..

trialGpuNumber: 1       # 每块 GPU 上多少个实验
trial_concurrency: 3    # 多少个实验一起跑


tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize

trainingService:
  platform: local
  maxTrialNumberPerGpu: 1
  useActiveGpu: true
  gpuIndices: [7,0,2]