defaults:
  - _self_
  - model: t5
  - tokenizer: rqvae

dataset: "Instruments"
output_dir: "/home/zsj/models/tigger-lr-1e-3"
cuda: "0"
force_retrain_tokenizer: false
force_retrain_model: false
skip_tokenizer: false
skip_model: false
skip_merge_train: false